pipeline:
  build:
    image: node:10
    secrets: [ AIRTABLE_KEY ]
    commands:
      - sh update.sh
      - cd ..
      - git init
      - git remote add origin https://github.com/eigenmethod/mam.git
      - git pull origin master
      - npm install
      - npm start piterjs/app
      - cd piterjs

  docker:
    image: plugins/docker
    repo: piterjs/piterjs.org
    dockerfile: Dockerfile
    tags: v2.0.0-${DRONE_COMMIT}
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: master

  kube:
    image: vallard/drone-kube
    template: deployment.yaml
    namespace: piterjs-org
    secrets: [ KUBE_TOKEN, KUBE_SERVER, KUBE_CA ]
    when:
      event: push
      branch: master

  notify:
    image: appleboy/drone-telegram
    format: markdown
    message: >
     {{#success build.status}}✅{{else}}❌{{/success}} Build {{build.status}}: *{{repo.owner}}/{{repo.name}}*
     build: {{build.number}}
     commit: {{commit.branch}}:{{commit.sha}}
     By: {{commit.author}}
     {{commit.message}}
     {{build.link}}
    secrets:
      - source: telegram_token
        target: telegram_token
      - source: telegram_to
        target: telegram_to
    when:
      event: push
      branch: master
