language: node_js
node_js:
  - "9"
install:
  - cd ..
  - git init
  - git remote add origin https://github.com/eigenmethod/mam.git
  - git pull origin master
  - npm install
script:
  - npm start piterjs/app
  - rm piterjs/.gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./app/-
  on:
    branch: master
