name: Deploy

on:
  workflow_dispatch:
  push:
  pull_request:
 
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Build app
      uses: hyoo-ru/mam_build@master2
      with:
        package: 'piterjs'
        modules: 'app'
    
    - name: Deploy on GitHub Pages
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      if: github.ref == 'refs/heads/master'
      with:
        repo-token: ${{ secrets.GH_PAT }}
        site-directory: 'piterjs/app/-'
